Repository w3c/vc-di-bbs, pull requests merged in 2024-04, with the labels that each got.

#147 Use v2 context for the data-integrity
  index.html
Labels: editorial, a11y-tracker, CR1

#148 Update auto-publish.yml for CR Drafts
  .github/workflows/auto-publish.yml
Labels: editorial, CR1

#158 Procedures update for optional features
  index.html
Labels: normative, CR1

#159 Correct small typo DataIntegrityProof not DataIntegirtyProof.
  index.html
Labels: editorial, CR1

#161 README.md Update
  README.md
Labels: editorial, CR1
